Refresh options
SteeltoeOSS/Steeltoe pull request #1198
Opened 2023-10-09 20:12 UTC by hananiel

## Description
Resolved the issue with updating configuration when IOptionsMonitor is used. As described in the issue, the `IOptionsChangeTokenSource` is not automatically registered when using some of provided extension methods. So we are registering it ourselves. 

I tried to eliminate the `Bind` method, but its not possible without passing around the IConfiguration to the service extension - so this is the next best alternative I found. 

Fixes #1174 

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [x] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

2023-10-10 13:59 UTC, hananiel commented
/azp run  cleanup-code

2023-10-11 14:07 UTC, bart-vmware commented on src/Management/src/Endpoint/Options/ConfigureEndpointOptions.cs
`Configuration.GetSection(_prefix).Bind(options);` (line 35) is the problematic part that needs to go away. It works the other way around. Instead of binding when `Configure` executes, options must have already been bound upfront, so the `Configure` method only changes existing properties instead of discarding what happened before. There can be multiple configure callbacks, right now only changes from the last one are applied.

2023-10-11 20:19 UTC, hananiel commented on src/Management/src/Endpoint/Options/ConfigureEndpointOptions.cs
If we don't do it here, where will it read from configuration? See this example for how its being done in microsoft code to implement` IConfigureOptions<T>` : They are not using the `Bind` method, but iterating over config [key/values].(https://github.com/dotnet/runtime/blob/8d2ada730b9a44aa630014eb0da1aa907e07c437/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/Configuration/MetricsConfigureOptions.cs#L97C26-L97C41) . Are you oppsed to the bind method or just reading from configuration at this point? This fires before any postconfigures so I dont see where there is anything changing before this except the notification that a configuration source has changed and we need to rebind.

2023-10-12 13:16 UTC, bart-vmware commented on src/Management/src/Endpoint/Options/ConfigureEndpointOptions.cs
> If we don't do it here, where will it read from configuration?

It happens automatically. As described at https://andrewlock.net/configuring-named-options-using-iconfigurenamedoptions-and-configureall/, the basic pattern is:
1. Connect options type to configuration path (optional, registers on change token):
    ```c#
    IServiceCollection services;
    services.Configure<MyOptions>(Configuration.GetSection("Path:To:MyOptions")); 
    ```
1. Configure options using callbacks, optional and potentially multiple times:
    ```c#
    IServiceCollection services;
    services.Configure<MyOptions>(options => options.Value += "X"); 
    services.Configure<MyOptions>(options => options.Value += "Y"); 
    services.PostConfigure<MyOptions>(options => options.Value += "Z"); 
    ```
1. Obtain singleton, snapshot or monitor:
    ```c#
    IServiceProvider serviceProvider;
    var snapshot = serviceProvider.GetRequiredService<IOptionsMonitor<MyOptions>>();
    ```

> See this example for how its being done in microsoft code to implement` IConfigureOptions<T>` : They are not using the `Bind` method, but iterating over config [key/values].(https://github.com/dotnet/runtime/blob/8d2ada730b9a44aa630014eb0da1aa907e07c437/src/libraries/Microsoft.Extensions.Diagnostics/src/Metrics/Configuration/MetricsConfigureOptions.cs#L97C26-L97C41).

That doesn't seem to follow the pattern. Perhaps they are doing it like that to support a more complicated configuration structure?

> Are you opposed to the bind method or just reading from configuration at this point?

Configurers generally shouldn't read from configuration, only update what was already provided. This enables callers to build the options from code instead of configuration, which is more flexible.

> This fires before any postconfigures so I dont see where there is anything changing before this except the notification that a configuration source has changed and we need to rebind.

See my example above, there could be multiple for various reasons.

2023-10-12 18:41 UTC, hananiel commented on src/Management/src/Endpoint/Options/ConfigureEndpointOptions.cs
Consider the alternative to this (what you consider "The pattern"). We will walk through configuring the Ioptions pattern using your preferred method: 


![Config](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/b9412edc-2606-4879-8c76-50f4298fb491)

Steps into the following sequentially: 

> Source : Microsoft.Extensions.Options.ConfigurationExtensions.nuget
>     -> public static class OptionsConfigurationServiceCollectionExtensions

![config2](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/75b105a3-f49e-4a13-8009-e03df320ffd8)
![config3](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/d7f5d97f-2e8c-495b-b268-00fd03993249)
![config4](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/baeeccc9-158c-4cb4-a57a-a970e6c82255)
> Source : Microsoft.Extensions.Options.ConfigurationExtensions.nuget
>   -> public class NamedConfigureFromConfigurationOptions<TOptions> : ConfigureNamedOptions<TOptions>
   
![config5](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/e4b6e4c6-b87e-4aa1-805a-a0b8637ef4a8)
>   -> public class NamedConfigureFromConfigurationOptions<TOptions> : ConfigureNamedOptions<TOptions>
![config6](https://github.com/SteeltoeOSS/Steeltoe/assets/887691/03d2fd55-4a5b-4d8b-afec-9d55e6680bd1)
>  -> public class ConfigureNamedOptions<TOptions> ...
Which is exactly what we were doing before. However I did miss adding the `IOptionsChangeTokenSource`. And since I copied your suggested changes, I think there is still a difference, but either way, I think I think binding to configuration in the configuremethod is fine - unless I am missing something else.

2023-10-17 11:25 UTC, bart-vmware commented on src/Management/src/Endpoint/Options/ConfigureEndpointOptions.cs
Thanks for taking the time to help me understand I was wrong. While documented as disparate mechanisms, under the covers it's using the same. So I now agree this change is the right solution.

2023-10-17 12:07 UTC, bart-vmware requested changes

2023-10-18 10:04 UTC, bart-vmware approved these changes
LGTM

2023-10-18 20:11 UTC, merged