Expose all actuators under the CloudFoundry context
SteeltoeOSS/Steeltoe pull request #1393
Opened 2024-10-30 01:26 UTC by TimHess

## Description

Skip the exposure check when building the list of exposed actuators under `/cloudfoundryapplication`

Fixes #1293 

## Quality checklist

- [ ] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [ ] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

2024-10-30 01:33 UTC, TimHess commented
/azp run cleanup-code

2024-10-30 06:38 UTC, bart-vmware commented on src/Management/test/Endpoint.Test/Actuators/Hypermedia/HypermediaEndpointTest.cs
> +        links.Entries.Should().BeEmpty();
```suggestion
        links.Entries.Should().BeEmpty();
```

`links.Entries.Should().BeEmpty()` already checks for not null, so `links.Entries.Should().NotBeNull()` is redundant.

2024-10-30 06:39 UTC, bart-vmware commented on src/Management/test/Endpoint.Test/Actuators/Hypermedia/HypermediaEndpointTest.cs
> +        links.Entries.Should().ContainKey("self");
```suggestion
        links.Entries.Should().ContainKey("self");
```

2024-10-30 06:43 UTC, bart-vmware commented on src/Management/test/Endpoint.Test/Actuators/Hypermedia/HypermediaEndpointTest.cs
> +        links.Entries.Should().BeEmpty();
```suggestion
        links.Entries.Should().BeEmpty();
```
- The `links` variable is declared as non-nullable, so `links.Should().NotBeNull()` looks redundant.
- `links.Entries.Should().BeEmpty()` already checks for not null, so `links.Entries.Should().NotBeNull()` is redundant.

2024-10-30 08:01 UTC, bart-vmware requested changes
While I appreciate the effort to convert xUnit assertions to FluentAssertions-style, it should be done with great care. Please carefully read https://fluentassertions.com/tips/, which lists how to write good assertions with FA. Simply converting existing assertions to FA-style syntax makes it questionable why to use the library in the first place.

When I checked a year ago, there existed two analyzers to help with the conversion and suggest better assertions. But when I tried them, they were buggy or had severe performance impact. I'd like to revisit this as part of #931.

2024-10-30 08:10 UTC, bart-vmware commented on src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs
To get rid of the cognitive complexity message, it's sufficient to extract a separate method:
```c#
private void AddToLinkEntries(string baseUrl, Links links, EndpointOptions endpointOptions)
{
    if (!string.IsNullOrEmpty(endpointOptions.Id))
    {
        if (!links.Entries.ContainsKey(endpointOptions.Id))
        {
            string linkPath = $"{baseUrl.TrimEnd('/')}/{endpointOptions.Path}";
            links.Entries.Add(endpointOptions.Id, new Link(linkPath));
        }
        else
        {
            _logger.LogWarning("Duplicate endpoint ID detected: {DuplicateEndpointId}", endpointOptions.Id);
        }
    }
}
```

2024-10-30 20:34 UTC, TimHess commented on src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs
This all sounds good to me, thanks - I'll push the changes

2024-10-30 20:37 UTC, TimHess commented
> While I appreciate the effort to convert xUnit assertions to FluentAssertions-style, it should be done with great care. Please carefully read https://fluentassertions.com/tips/, which lists how to write good assertions with FA. Simply converting existing assertions to FA-style syntax makes it questionable why to use the library in the first place.
> 
> When I checked a year ago, there existed two analyzers to help with the conversion and suggest better assertions. But when I tried them, they were buggy or had severe performance impact. I'd like to revisit this as part of #931.

I did try to change most/all of the assertions in a file when I ran into stupid test failure messages (false should be true, etc) so we'd at least be closer to where we want to be here, but admittedly put very little effort into true improvements... I'm sure I've _read_ those tips before, but clearly haven't fully absorbed them, so I've bookmarked the page and will attempt to keep them in mind in the future, thanks.

2024-10-31 07:11 UTC, bart-vmware submitted a review, later dismissed
LGTM, aside from build errors

2024-10-31 13:49 UTC, bart-vmware approved these changes

2024-10-31 13:59 UTC, merged