Bootstrap logger
SteeltoeOSS/Steeltoe pull request #803
Opened 2021-10-21 04:30 UTC by macsux

Adds bootstrap logger that can be statically accessed for access to logging infrastructure before service container is built. It supports "upgrades" as infrastructure is loaded, primarily via call to update it with IConfiguration and after container is constructed ILoggerFactory. Any existing loggers spawned from it are seamlessly upgraded. Refactored config server to take advantage of this implementation if explicit LoggerFactory is not specified.

@hananiel you should probably look at this one as it touches stuff you recently worked on

2021-11-03 20:05 UTC, TimHess requested changes

2021-11-03 20:05 UTC, TimHess commented on src/Common/src/Common/Logging/UpgradableBootstrapLoggerFactory.cs
> +        // private static readonly BootstrapLoggerFactoryInst _bootstrapFactory = new ();
What's happening with these comments?

2021-11-03 20:05 UTC, TimHess commented on src/Common/src/Common/Logging/UpgradableBootstrapLoggerFactory.cs
> +    internal class UpgradableBootstrapLoggerFactory : IBoostrapLoggerFactory
Need to address S3881 or ignore with simple explanation

2021-11-08 15:18 UTC, hananiel reviewed
Looks fine, pending @TimHess's comments.

2022-02-23 18:35 UTC, dtillman approved these changes
LGTM

2022-02-23 20:32 UTC, TimHess approved these changes

2022-02-23 20:34 UTC, TimHess commented
/azp run Steeltoe.All

2022-02-24 20:12 UTC, merged