Add WebApplicationBuilder Extensions, improve .NET 6 compatibility
SteeltoeOSS/Steeltoe pull request #824
Opened 2022-01-24 21:01 UTC by TimHess

2022-01-24 21:35 UTC, TimHess commented
/azp run Steeltoe.All

2022-01-31 14:37 UTC, lvendramini commented
Is .Net 6 supported?  How do we add steeltoe to .net 6 program.cs?

2022-01-31 18:12 UTC, TimHess commented
> Is .Net 6 supported? How do we add steeltoe to .net 6 program.cs?

Thanks for the question... This PR primarily adds extensions to use with the new `WebApplicationBuilder`, otherwise `HostBuilder` and `WebHostBuilder` can both still be used in .NET 6. Additionally, it is possible to use most of the other pre-existing Steeltoe setup methods with WebApplication by using them on the `.Configuration` or `.Services` properties of the builder, eg:

```
builder.Configuration.AddConfigServer();
builder.Logging.AddDynamicConsole();
builder.Services.AddAllActuators(builder.Configuration);
builder.Services.ActivateActuatorEndpoints();
```

I believe the only known issue with Steeltoe on .NET 6 (which is addressed in this PR) is that there is potential for recursion with the placeholder config provider.

2022-01-31 19:55 UTC, lvendramini commented
> > Is .Net 6 supported? How do we add steeltoe to .net 6 program.cs?
> 
> Thanks for the question... This PR primarily adds extensions to use with the new `WebApplicationBuilder`, otherwise `HostBuilder` and `WebHostBuilder` can both still be used in .NET 6. Additionally, it is possible to use most of the other pre-existing Steeltoe setup methods with WebApplication by using them on the `.Configuration` or `.Services` properties of the builder, eg:
> 
> ```
> builder.Configuration.AddConfigServer();
> builder.Logging.AddDynamicConsole();
> builder.Services.AddAllActuators(builder.Configuration);
> builder.Services.ActivateActuatorEndpoints();
> ```
> 
> I believe the only known issue with Steeltoe on .NET 6 (which is addressed in this PR) is that there is potential for recursion with the placeholder config provider.

In our Program.cs we have
using Steeltoe.Extensions.Configuration.CloudFoundry;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.**AddConfigServer**();
builder.Logging.**AddDynamicConsole**();
builder.Services.**AddAllActuators**(builder.Configuration);
builder.Services.**ActivateActuatorEndpoints**();

But none of the bolded entries are know.  What else do we need? Thanks!

2022-01-31 20:44 UTC, TimHess commented
> > > Is .Net 6 supported? How do we add steeltoe to .net 6 program.cs?
> > 
> > 
> > Thanks for the question... This PR primarily adds extensions to use with the new `WebApplicationBuilder`, otherwise `HostBuilder` and `WebHostBuilder` can both still be used in .NET 6. Additionally, it is possible to use most of the other pre-existing Steeltoe setup methods with WebApplication by using them on the `.Configuration` or `.Services` properties of the builder, eg:
> > ```
> > builder.Configuration.AddConfigServer();
> > builder.Logging.AddDynamicConsole();
> > builder.Services.AddAllActuators(builder.Configuration);
> > builder.Services.ActivateActuatorEndpoints();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe the only known issue with Steeltoe on .NET 6 (which is addressed in this PR) is that there is potential for recursion with the placeholder config provider.
> 
> In our Program.cs we have using Steeltoe.Extensions.Configuration.CloudFoundry;
> 
> var builder = WebApplication.CreateBuilder(args);
> 
> builder.Configuration.**AddConfigServer**(); builder.Logging.**AddDynamicConsole**(); builder.Services.**AddAllActuators**(builder.Configuration); builder.Services.**ActivateActuatorEndpoints**();
> 
> But none of the bolded entries are know. What else do we need? Thanks!

Assuming you've already got the nuget references (EndpointCore and ConfigServerBase or Core for these, other components would be different), adding these usings should work. Visual Studio should be able to find them via `CTRL` + `.` suggestions too
```
using Steeltoe.Extensions.Configuration.ConfigServer;
using Steeltoe.Extensions.Logging;
using Steeltoe.Management.Endpoint;
```

2022-02-01 17:43 UTC, lvendramini commented
> > > > Is .Net 6 supported? How do we add steeltoe to .net 6 program.cs?
> > > 
> > > 
> > > Thanks for the question... This PR primarily adds extensions to use with the new `WebApplicationBuilder`, otherwise `HostBuilder` and `WebHostBuilder` can both still be used in .NET 6. Additionally, it is possible to use most of the other pre-existing Steeltoe setup methods with WebApplication by using them on the `.Configuration` or `.Services` properties of the builder, eg:
> > > ```
> > > builder.Configuration.AddConfigServer();
> > > builder.Logging.AddDynamicConsole();
> > > builder.Services.AddAllActuators(builder.Configuration);
> > > builder.Services.ActivateActuatorEndpoints();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I believe the only known issue with Steeltoe on .NET 6 (which is addressed in this PR) is that there is potential for recursion with the placeholder config provider.
> > 
> > 
> > In our Program.cs we have using Steeltoe.Extensions.Configuration.CloudFoundry;
> > var builder = WebApplication.CreateBuilder(args);
> > builder.Configuration.**AddConfigServer**(); builder.Logging.**AddDynamicConsole**(); builder.Services.**AddAllActuators**(builder.Configuration); builder.Services.**ActivateActuatorEndpoints**();
> > But none of the bolded entries are know. What else do we need? Thanks!
> 
> Assuming you've already got the nuget references (EndpointCore and ConfigServerBase or Core for these, other components would be different), adding these usings should work. Visual Studio should be able to find them via `CTRL` + `.` suggestions too
> 
> ```
> using Steeltoe.Extensions.Configuration.ConfigServer;
> using Steeltoe.Extensions.Logging;
> using Steeltoe.Management.Endpoint;
> ```

Thanks that worked.  Will that allow us to host our service in Pivotal Cloud Foundry?  So far it does not work...  Before .net 6 we had in the startup 
`      public static IWebHost CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseCloudFoundryHosting()
                .UseDefaultServiceProvider(options => options.ValidateScopes = false)
                .ConfigureAppConfiguration((builderContext, configBuilder) =>
                {
                    configBuilder.AddCloudFoundry();
                }).Build();
`

Does the following allow the service to be containerized in PCF?  Or are we missing something?
 builder.Configuration.AddConfigServer();
builder.Logging.AddDynamicConsole();
builder.Services.AddAllActuators(builder.Configuration);
builder.Services.ActivateActuatorEndpoints();

2022-02-02 15:53 UTC, TimHess commented
> > > > > Is .Net 6 supported? How do we add steeltoe to .net 6 program.cs?
> > > > 
> > > > 
> > > > Thanks for the question... This PR primarily adds extensions to use with the new `WebApplicationBuilder`, otherwise `HostBuilder` and `WebHostBuilder` can both still be used in .NET 6. Additionally, it is possible to use most of the other pre-existing Steeltoe setup methods with WebApplication by using them on the `.Configuration` or `.Services` properties of the builder, eg:
> > > > ```
> > > > builder.Configuration.AddConfigServer();
> > > > builder.Logging.AddDynamicConsole();
> > > > builder.Services.AddAllActuators(builder.Configuration);
> > > > builder.Services.ActivateActuatorEndpoints();
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I believe the only known issue with Steeltoe on .NET 6 (which is addressed in this PR) is that there is potential for recursion with the placeholder config provider.
> > > 
> > > 
> > > In our Program.cs we have using Steeltoe.Extensions.Configuration.CloudFoundry;
> > > var builder = WebApplication.CreateBuilder(args);
> > > builder.Configuration.**AddConfigServer**(); builder.Logging.**AddDynamicConsole**(); builder.Services.**AddAllActuators**(builder.Configuration); builder.Services.**ActivateActuatorEndpoints**();
> > > But none of the bolded entries are know. What else do we need? Thanks!
> > 
> > 
> > Assuming you've already got the nuget references (EndpointCore and ConfigServerBase or Core for these, other components would be different), adding these usings should work. Visual Studio should be able to find them via `CTRL` + `.` suggestions too
> > ```
> > using Steeltoe.Extensions.Configuration.ConfigServer;
> > using Steeltoe.Extensions.Logging;
> > using Steeltoe.Management.Endpoint;
> > ```
> 
> Thanks that worked. Will that allow us to host our service in Pivotal Cloud Foundry? So far it does not work... Before .net 6 we had in the startup ` public static IWebHost CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args) .UseStartup<Startup>() .UseCloudFoundryHosting() .UseDefaultServiceProvider(options => options.ValidateScopes = false) .ConfigureAppConfiguration((builderContext, configBuilder) => { configBuilder.AddCloudFoundry(); }).Build();`
> 
> Does the following allow the service to be containerized in PCF? Or are we missing something? builder.Configuration.AddConfigServer(); builder.Logging.AddDynamicConsole(); builder.Services.AddAllActuators(builder.Configuration); builder.Services.ActivateActuatorEndpoints();

Could you please open a separate issue, listing all of the Steeltoe components you're wanting to use and ideally a complete sample?

2022-02-04 19:51 UTC, hananiel requested changes

2022-02-04 19:51 UTC, hananiel commented on src/Configuration/src/KubernetesBase/KubernetesServiceCollectionExtensions.cs
> +        /// Adds KubernetesApplicationInstanceInfo and ensures runtime loggers are used
```suggestion
        /// Adds KubernetesApplicationInstanceInfo and ensures startup loggers are replaced by runtime loggers
```

2022-02-04 19:52 UTC, hananiel approved these changes

2022-02-09 18:32 UTC, hananiel approved these changes

2022-02-09 18:36 UTC, merged