Promote bootstrap logger to public API
SteeltoeOSS/Steeltoe pull request #894
Opened 2022-07-26 18:34 UTC by macsux

Promote bootstrap logger to public API. Improve intellisense

2022-07-26 19:03 UTC, ccheetham commented on src/Common/src/Common/Logging/BootstrapLoggerFactory.cs
> +/// Provides access to logging infrastructure before service container is created. Any loggers created are upgraded with config settings after
Should "upgraded " be "updated"?

2022-07-26 19:03 UTC, ccheetham commented on src/Common/src/Common/Logging/BootstrapLoggerFactory.cs
> +/// </summary>
"service container" seems odd.  If it's a singleton, would Service Container be better?  Or perhaps "the service container."

2022-07-26 19:03 UTC, ccheetham commented on src/Common/src/Common/Logging/UpgradableBootstrapLoggerFactory.cs
> +/// This class should only be used by components that need logging logging infrastructure before service container is available.
ditto above

2022-07-27 09:52 UTC, bart-vmware requested changes

2022-07-27 09:52 UTC, bart-vmware commented on src/Common/src/Common/Logging/BootstrapLoggerFactory.cs
> +/// This class should only be used by components that need logging logging infrastructure before Service Container is available.
```suggestion
/// This class should only be used by components that need logging infrastructure before Service Container is available.
```

2022-07-27 09:52 UTC, bart-vmware commented on src/Common/src/Common/Logging/UpgradableBootstrapLoggerFactory.cs
> +/// This class should only be used by components that need logging logging infrastructure before Service Container is available.
```suggestion
/// This class should only be used by components that need logging infrastructure before Service Container is available.
```

2022-07-27 12:30 UTC, bart-vmware approved these changes

2022-07-27 21:16 UTC, TimHess commented
/azp run Steeltoe.All

2022-07-28 13:12 UTC, merged